### ISSUE TITLE
Exit status 130 on postinstall

### ISSUE THREAD

**Issue by domi41** [opencollective/opencollective-postinstall#7]
Hello ! Trying to install the latest sovereign, we get this :

```
$ meteor npm update

> opencollective-postinstall@1.1.1 postinstall /home/domi/code/snd/sovereign/node_modules/opencollective-postinstall
> node bin/setup.js

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/domi/.meteor/packages/meteor-tool/.1.4.3_2.gb4cf5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/domi/.meteor/packages/meteor-tool/.1.4.3_2.gb4cf5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "update"
npm ERR! node v4.8.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 130

npm ERR! opencollective-postinstall@1.1.1 postinstall: `node bin/setup.js`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the opencollective-postinstall@1.1.1 postinstall script 'node bin/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencollective-postinstall package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencollective-postinstall
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencollective-postinstall
npm ERR! There is likely additional logging output above.
```

It looks similar to the closed issue with Heroku.
The `postinstall` script directive of the `package.json` of sovereign does have the `|| exit 0` suffix.

We're confused ; Exit code `130` customarily means _"Script terminated by Control-C"_, which we promise we did not. Is it possible that it's an encoding issue and incredible back luck ? (a char that would convert to CTRL+C in another encoding ? Shaking the trees, here)
We're running the head of the master of sovereign. _(note how this sentence does not make any sense without the context :smile: )_

**Comment by keith24** [comment]
I'm getting this too, with node v8.4.0 and npm v5.3.0.  Here's the additional logging output:  

```
7525 silly postinstall nan@2.7.0
7526 info lifecycle nan@2.7.0~postinstall: nan@2.7.0
7527 silly postinstall opencollective-postinstall@1.1.1
7528 info lifecycle opencollective-postinstall@1.1.1~postinstall: opencollective-postinstall@1.1.1
7529 verbose lifecycle opencollective-postinstall@1.1.1~postinstall: unsafe-perm in lifecycle true
7530 verbose lifecycle opencollective-postinstall@1.1.1~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/keith/code/meteor/sovereign/node_modules/opencollective-postinstall/node_modules/.bin:/home/keith/code/meteor/sovereign/node_modules/.bin:/home/keith/bin:/home/keith/.local/bin:/home/keith/bin:/home/keith/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/keith/.android/sdk/tools:/home/keith/.android/sdk/tools/bin:/home/keith/.android/sdk/build-tools:/home/keith/.android/sdk/platform-tools:/snap/bin:/home/keith/.android/sdk/tools:/home/keith/.android/sdk/tools/bin:/home/keith/.android/sdk/build-tools:/home/keith/.android/sdk/platform-tools
7531 verbose lifecycle opencollective-postinstall@1.1.1~postinstall: CWD: /home/keith/code/meteor/sovereign/node_modules/opencollective-postinstall
7532 silly lifecycle opencollective-postinstall@1.1.1~postinstall: Args: [ '-c', 'node bin/setup.js' ]
7533 silly lifecycle opencollective-postinstall@1.1.1~postinstall: Returned: code: 130  signal: null
7534 info lifecycle opencollective-postinstall@1.1.1~postinstall: Failed to exec postinstall script
7535 verbose unlock done using /home/keith/.npm/_locks/staging-10255b915ad19a04.lock for /home/keith/code/meteor/sovereign/node_modules/.staging
7536 verbose stack Error: opencollective-postinstall@1.1.1 postinstall: `node bin/setup.js`
7536 verbose stack Exit status 130
7536 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
7536 verbose stack     at emitTwo (events.js:125:13)
7536 verbose stack     at EventEmitter.emit (events.js:213:7)
7536 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
7536 verbose stack     at emitTwo (events.js:125:13)
7536 verbose stack     at ChildProcess.emit (events.js:213:7)
7536 verbose stack     at maybeClose (internal/child_process.js:927:16)
7536 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
7537 verbose pkgid opencollective-postinstall@1.1.1
7538 verbose cwd /home/keith/code/meteor/sovereign
7539 verbose Linux 4.4.0-93-generic
7540 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
7541 verbose node v8.4.0
7542 verbose npm  v5.3.0
7543 error code ELIFECYCLE
7544 error errno 130
7545 error opencollective-postinstall@1.1.1 postinstall: `node bin/setup.js`
7545 error Exit status 130
7546 error Failed at the opencollective-postinstall@1.1.1 postinstall script.
7546 error This is probably not a problem with npm. There is likely additional logging output above.
7547 verbose exit [ 130, true ]
```

**Comment by domi41** [comment]
It's possible to make this issue non-blocking by _locally removing_ (alas! JSON has no comments) the two lines related to `postinstall` from sovereign's `package.json`.

Still having this issue as well. 

```
node v4.8.4
npm  v4.6.1
```

**Comment by znarf** [comment]
This bug was related to previous recommended installation steps. Seems like the new one don't have the same problem.

```
"scripts": {
  "postinstall": "opencollective-postinstall"
},
```
